name: documentation
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  createDocs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Generate docs backend-api
        run: nx run backend-api:compodoc
      - name: Generate docs frontend-admin
        run: nx run frontend-admin:compodoc
      - name: Generate docs frontend-client
        run: nx run frontend-client:compodoc

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GH_PAGE }}
